[tool.poetry]
name = "nornir_tests"
version = "0.1.0"
description = ""
authors = ["Patrick Avery <patrickdaj@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
nornir = {version = "^3.0.0-beta.1", allow-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
nornir_utils = "^0.1.0"
jupyter = "^1"
ipdb = "^0.13.3"
black = "^20.8b1"
mypy = "^0.782"
pylama = "^7.7.1"
pytest-coverage = "^0.0"
nbval = "*"
sphinx = "^3.0.3"
sphinxcontrib-napoleon = "^0.7"
nbsphinx = "^0.6.1"
sphinx-issues = "^1.2.0"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
